# Generated by Django 2.2.4 on 2019-08-07 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20190807_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='news',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='news.Article'),
        ),
    ]
